name: easy_storage
description: "Storage package for easy upload into Firebase"
version: 0.0.1
homepage: https://github.com/thruthesky/easy_storage

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: 5.1.0
  firebase_auth: 5.1.2
  firebase_core: 3.2.0
  firebase_storage: 12.1.1
  flutter:
    sdk: flutter
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
